export const navigationLinks = [
    // { name: "Dashboard", link: false, border: false },
    // {
    //     name: "Dashboard",
    //     link: true,
    //     border: false,
    //     startWith: "/dashboard",
    //     route: "dashboard",
    //     icon: "ChartPieIcon",
    // },
    { name: "User Management", link: false, border: false },
    {
        name: "Users",
        link: true,
        border: false,
        startWith: "/admin/dashboard",
        route: "admin.index",
        icon: "SwatchIcon",
    },
    // {
    //     name: "Customers",
    //     link: true,
    //     border: false,
    //     startWith: "/customers",
    //     route: "dashboard",
    //     icon: "UsersIcon",
    // },
    { name: "Shop Management", link: false, border: true },
    {
        name: "Shop Details",
        link: true,
        border: false,
        startWith: "/user/shop/dashboard",
        route: "shop.index",
        icon: "ShieldCheckIcon",
    }, {
        name: "Food Details",
        link: true,
        border: false,
        startWith: "/user/shop/food",
        route: "food.index",
        icon: "ShieldCheckIcon",
    },
    // { name: "Auction Management", link: false, border: true },
    // {
    //     name: "Customer Bets",
    //     link: true,
    //     border: false,
    //     startWith: "/customerBets",
    //     route: "dashboard",
    //     icon: "Squares2X2Icon",
    // },
    // { name: "Inquiries Management", link: false, border: true },
    // {
    //     name: "Inquiries",
    //     link: true,
    //     border: false,
    //     startWith: "/inquiries",
    //     route: "dashboard",
    //     icon: "ChatBubbleOvalLeftEllipsisIcon",
    // },
    // { name: "Other", link: false, border: true },
    // {
    //     name: "Profile Settings",
    //     link: true,
    //     border: false,
    //     startWith: "/profile",
    //     route: "profile.edit",
    //     icon: "ShieldExclamationIcon",
    // },
];
